"""empty message

Revision ID: c45fa531ea1b
Revises: ade8baef8dcf
Create Date: 2023-12-03 16:47:56.207337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c45fa531ea1b'
down_revision = 'ade8baef8dcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reaction_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reaction_groups'))
    )
    op.create_table('reaction_subgroups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('subgroup_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['reaction_groups.id'], name=op.f('fk_reaction_subgroups_group_id_reaction_groups')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reaction_subgroups'))
    )
    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subgroup_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_reactions_subgroup_id_reaction_subgroups'), 'reaction_subgroups', ['subgroup_id'], ['id'])
        batch_op.drop_column('subgroup')
        batch_op.drop_column('group')

    with op.batch_alter_table('user_reactions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_reactions_message_id_user_id_reaction_id', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_reactions', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_reactions_message_id_user_id_reaction_id', ['user_id', 'message_id', 'reaction_id'])

    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('subgroup', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_reactions_subgroup_id_reaction_subgroups'), type_='foreignkey')
        batch_op.drop_column('subgroup_id')

    op.drop_table('reaction_subgroups')
    op.drop_table('reaction_groups')
    # ### end Alembic commands ###
