"""empty message

Revision ID: b37fd4941e43
Revises: c45fa531ea1b
Create Date: 2023-12-03 18:02:59.838289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b37fd4941e43'
down_revision = 'c45fa531ea1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_reactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_reactions', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
