"""empty message

Revision ID: ade8baef8dcf
Revises: 2d2234949533
Create Date: 2023-12-01 13:13:17.385305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ade8baef8dcf'
down_revision = '2d2234949533'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_reactions', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_reactions_message_id_user_id_reaction_id', ['user_id', 'message_id', 'reaction_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_reactions', schema=None) as batch_op:
        batch_op.drop_unique_constraint('uq_user_reactions_message_id_user_id_reaction_id')
