"""empty message

Revision ID: baa15c565301
Revises: 9d5a9f86973b
Create Date: 2023-12-08 22:19:49.639536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baa15c565301'
down_revision = '9d5a9f86973b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_reactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_reactions_message_id_messages', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_reactions_message_id_messages'), 'messages', ['message_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_reactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_reactions_message_id_messages'), type_='foreignkey')
        batch_op.create_foreign_key('fk_user_reactions_message_id_messages', 'messages', ['message_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
